# Generated by Django 4.2.30 on 2026-06-05 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=200)),
                ('harga', models.IntegerField()),
                ('deskripsi', models.TextField()),
                ('spesifikasi', models.TextField(blank=True, null=True)),
                ('stok', models.IntegerField(default=0)),
                ('tanggal_input', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
