# Generated by Django 4.2.30 on 2026-06-05 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('katalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produk',
            name='garansi',
            field=models.IntegerField(default=0, help_text='Isi dengan angka tahun. Contoh: 0 untuk tidak ada, 1 untuk 1 tahun.'),
        ),
    ]
